#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-2.0-or-later
# Reuse exactly one O= directory. Ordinary invocations are incremental.
set -euo pipefail

repo_root=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)
hikari_build_root=${HIKARI_BUILD_ROOT:-/home/paul/xperia/build}
kernel_build=${KERNEL_BUILD:-"$hikari_build_root/linux-hikari-current"}
base_fragment="$repo_root/kernel/configs/hikari-boot6-display.fragment"
debian_fragment="$repo_root/kernel/configs/hikari-debian.fragment"
root_initramfs="$hikari_build_root/hikari-root-initramfs-current/hikari-root.cpio.gz"

# gen_init_cpio is a host tool generated by the kernel build itself.
HIKARI_BUILD_ROOT="$hikari_build_root" BUILD_DIR="$kernel_build" \
	KERNEL_FRAGMENT="$base_fragment" KERNEL_EXTRA_FRAGMENTS="$debian_fragment" \
	PRUNE_DEFAULT_MODULES=1 \
	REQUIRE_USB_DEBUG=1 REQUIRE_DISPLAY_BRINGUP=1 REQUIRE_CHARGING=1 \
	TARGETS=usr/ "$repo_root/scripts/build-hikari-kernel.sh"

HIKARI_BUILD_ROOT="$hikari_build_root" \
	GEN_INIT_CPIO="$kernel_build/usr/gen_init_cpio" \
	"$repo_root/scripts/build-hikari-root-initramfs.sh"

HIKARI_BUILD_ROOT="$hikari_build_root" BUILD_DIR="$kernel_build" \
	KERNEL_FRAGMENT="$base_fragment" KERNEL_EXTRA_FRAGMENTS="$debian_fragment" \
	PRUNE_DEFAULT_MODULES=1 \
	INITRAMFS_SOURCE="$root_initramfs" \
	REQUIRE_USB_DEBUG=1 REQUIRE_DISPLAY_BRINGUP=1 REQUIRE_CHARGING=1 \
	TARGETS='zImage modules qcom/qcom-msm8260-sony-hikari.dtb' \
	"$repo_root/scripts/build-hikari-kernel.sh"

printf 'HIKARI_DEBIAN_KERNEL=PASS\nbuild=%s\ninitramfs=%s\n' "$kernel_build" "$root_initramfs"
