Section "ServerFlags"
 Option "AutoAddGPU" "false"
 Option "DontVTSwitch" "false"
EndSection
Section "Module"
 Disable "glx"
 Disable "dri"
 Disable "dri2"
EndSection
Section "Device"
 Identifier "hikari-cpu"
 Driver "modesetting"
 Option "kmsdev" "/dev/dri/card0"
 Option "AccelMethod" "none"
 Option "ShadowFB" "true"
 Option "SWcursor" "true"
EndSection
Section "Screen"
 Identifier "hikari-screen"
 Device "hikari-cpu"
 DefaultDepth 24
EndSection
Section "InputClass"
 Identifier "hikari-touch"
 MatchProduct "Synaptics TM1964-001"
 MatchIsTouchscreen "on"
 Driver "libinput"
 Option "CalibrationMatrix" "1 0 0 0 1 0 0 0 1"
EndSection
